# HW1

##### 1. How to count the number of elements in a list in Python?

In [1]:
newList = [1, 2, 3, 4, 5]
length = len(newList)
print(length)

5


##### 2. Create a list with random values in Python.

In [4]:
import random

newList = [random.randint(0, 100) for i in range(10)]
newList

[99, 46, 57, 7, 31, 13, 19, 89, 90, 75]

##### 3. How to add a key-value pair to a dictionary in Python?

In [5]:
dictionary = {'key1': 'value1', 'key2': 'value2', 'key3': 'value3'}
dictionary

{'key1': 'value1', 'key2': 'value2', 'key3': 'value3'}

##### 4. Access index names of a list using the enumerate function in Python.

In [7]:
sampleList = ['a',  'b', 'c', 'd', 'e']
for index, element in enumerate(sampleList):
    print(index, element)

0 a
1 b
2 c
3 d
4 e


##### 5. Convert a matrix to a list of lists in Python.

In [8]:
import numpy as np

matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])
list = matrix.tolist()
list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

##### 7. Convert a list to a NumPy array in Python.

In [10]:
list = [1, 2, 3, 4, 5]
array = np.array(list)
array

array([1, 2, 3, 4, 5])

##### 8. Use a for loop to print the elements of a list in Python.

In [11]:
list = [1, 2, 3, 4, 5]

for i in list:
    print(i)

1
2
3
4
5


##### 9. Find the sum of elements in a list using a for loop in Python.

In [12]:
sum = 0
list = [1,2,3,4,5,6,7,8,9,10]

for i in list:
    sum += i
    
print(sum)

55


##### 10. Find the maximum value in a list using a for loop in Python.

In [13]:
list = [1,2,3,4,5,6,7,8,9,10]
max = list[0]

for i in list:
    if i > max:
        max = i

print(max)

10


##### 11. Reverse a list using a for loop in Python.

In [20]:
list = [1,2,3,4,5,6,7,8,9,10]
reversedList = list[-1::-1]
print(reversedList)

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


##### 12. Count the number of even and odd elements in a list using a for loop in Python.

In [21]:
list = [1,2,3,4,5,6,7,8,9,10]

even = 0
odd = 0

for i in list:
    if i % 2 == 0:
        even += 1
    else:
        odd += 1

print("Even numbers: ", even)
print("Odd numbers: ", odd)

Even numbers:  5
Odd numbers:  5


##### 13. Use a while loop to print the elements of a list in Python.

In [22]:
list = [1,2,3,4,5,6,7,8,9,10]

i = 0

while i < len(list):
    print(list[i])
    i += 1

1
2
3
4
5
6
7
8
9
10


##### 14. Use a while loop to find the first occurrence of a specific element in a list in Python.

In [3]:
list = [1,2,3,4,5,6,7,8,9,10]

i = 0

while i < len(list):
    print(list[i])
    if list[i] == 3:
        print("3 found at index", i)
        break
    i += 1

1
2
3
3 found at index 2


##### 15. Use a while loop to calculate the factorial of a number in Python.

In [2]:
number = int(input("Enter a number: "))

i = 0
factorial = 1

while i < number:
    i += 1
    factorial *= i

print(f"The factorial of {number} is {factorial}")

The factorial of 3 is 6


##### 16. Use a while loop to calculate the square of numbers in Python.

In [9]:
list = [1,2,3,4,5,6,7,8,9,10]

i = 0

while i < len(list):
    square = list[i] ** 2
    print(square)
    i += 1

1
4
9
16
25
36
49
64
81
100


##### 17. Use a while loop to reverse a string in Python.

In [12]:
word = "Hello World"

i = len(word)

while i > 0:
    print(word[i-1], end="")
    i -= 1

dlroW olleH

##### 18. Use nested for loops to print multiplication tables up to a certain number in Python.

In [14]:
for i in range(1, 6):
    for j in range(1,11):
        product = i * j
        print(f"{i} * {j} = {product}")

1 * 1 = 1
1 * 2 = 2
1 * 3 = 3
1 * 4 = 4
1 * 5 = 5
1 * 6 = 6
1 * 7 = 7
1 * 8 = 8
1 * 9 = 9
1 * 10 = 10
2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
2 * 10 = 20
3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27
3 * 10 = 30
4 * 1 = 4
4 * 2 = 8
4 * 3 = 12
4 * 4 = 16
4 * 5 = 20
4 * 6 = 24
4 * 7 = 28
4 * 8 = 32
4 * 9 = 36
4 * 10 = 40
5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
5 * 10 = 50


##### 19. Use nested for loops to create a 2D matrix in Python.

In [15]:
import numpy as np

rows = int(input("Enter the number of rows for the Matrix: "))
columns = int(input("Enter the number of columns for the Matrix: "))

matrix = np.empty((rows, columns))

for i in range(rows):
    for j in range(columns):
        matrix[i][j] = int(input(f"Enter the value for [{i}][{j}]: "))
        
print(matrix)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


##### 21. Use nested for loops to calculate the transpose of a matrix in Python.

In [18]:
import numpy as np

matrix = np.matrix([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

transpose = matrix.T

print(transpose)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


##### 22. Check if a number is positive or negative using if-else statements in Python.

In [19]:
number = int(input("Enter a number: "))

if number > 0:
    print("Positive")
elif number < 0:
    print("Negative")
else:
    print("Zero")

Positive


##### 23. Use if-else statements to find the maximum of two numbers in Python.

In [21]:
number1 = int(input("Enter first number: "))
number2 = int(input("Enter second number: "))

if number1 > number2:
    print(f"{number1} is the maximum of {number1} & {number2}")
else:
    print(f"{number2} is the maximum of {number1} & {number2}")

5 is the maximum of 5 & 2


##### 24. Create a program to assign grades based on a student’s score using if-else statements in Python.

In [22]:
grade = int(input("Enter your grade: "))

if grade >= 90:
    print("A")
elif (grade >= 80) and (grade < 90):
    print("B")
elif (grade >= 70) and (grade < 80):
    print("C")
elif (grade >= 60) and (grade < 70):
    print("D")
else:
    print("E")

B


##### 25. Create a program to categorize numbers into odd or even using if-else statements in Python.

In [24]:
list = [1,2,3,4,5,6,7,8,9,10]

evenList = []
oddList = []

for i in list:
    if i % 2 == 0:
        evenList.append(i)
    else:
        oddList.append(i)

print(f'Even List: {evenList}')
print(f'Odd List: {oddList}')

Even List: [2, 4, 6, 8, 10]
Odd List: [1, 3, 5, 7, 9]


##### 26. Use if-else statements to check if a number is divisible by another number in Python.

In [25]:
numerator = int(input("Enter the numerator: "))
denominator = int(input("Enter the denominator: "))

if denominator == 0:
    print("Cannot divide by zero!")
elif numerator == 0:
    print("0")
elif numerator % denominator == 0:
    print(f'{numerator} is divisible by {denominator}')
else:
    print(f'{numerator} is not divisible by {denominator}')

7 is not divisible by 3


##### 27. Use if-else statements to categorize ages into different groups in Python.

In [26]:
age = int(input("Enter your age: "))

if age<=1 and age>=0:
    print("Infant")
elif age>=2 and age<=12:
    print("Child")
elif age>=13 and age<=19:
    print("Teenager")
else:
    print("Adult")

Child


##### 28. Use if-else statements to check if a string contains a specific substring in Python.

In [27]:
string = input("Enter a string: ")
substring = input("Enter a substring: ")

if substring in string:
    print(f"{substring} is in {string}")
else:
    print(f"{substring} is not in {string}")

hell is in hello
